### ISSUE TITLE
Failed To Build Docker Container

### ISSUE THREAD

**Issue by hharnisc** [fission-suite/ipfs-api#3]
## Expected Behavior
Container completes build cycle.

## Current Behavior

```shell
Step 3/17 : COPY ipfs-api.cabal /opt/fission-ipfs-api
COPY failed: stat /var/lib/docker/tmp/docker-builder781992172/ipfs-api.cabal: no such file or directory
```
## Possible Solution

Not sure, perhaps a missing step or a file I'm missing 😄 

## Steps to Reproduce (for bugs)

1. `git clone git@github.com:fission-suite/ipfs-api.git`
2. `cd ipfs-api`
3. `docker build -t expede/fission .`

## Context

Was trying to run the quickstart.

## Your Environment
* Version used: SHA: 0436e9077223884db166092a08dc85c40292b30f
* Operating System and version (desktop or mobile): OS X 10.14.4 (18E226)

**Comment by expede** [comment]
Thanks for the report @hharnisc! I should also mention that this app doesn't do much yet  😅 (Hopefully in the next few days it'll have more functionality.) Very much appreciate the interest, though 🙌
